const APP={
  brand:'Vínculo · Psicología Online', therapist:'Ps. Nombre Apellido', credential:'Psicóloga · Registro profesional por configurar',
  domain:'https://TU-DOMINIO.CL', calBookingUrl:'', payBeforeBooking:true,
  services:[
    {id:'first',name:'Primera entrevista',minutes:50,price:30000,desc:'Conocer tu motivo de consulta y definir próximos pasos.'},
    {id:'individual',name:'Sesión individual',minutes:50,price:30000,desc:'Seguimiento psicológico online para adultos.'},
    {id:'orientation',name:'Sesión de orientación',minutes:30,price:22000,desc:'Espacio acotado para ordenar una situación y decidir cómo continuar.'}
  ]
};
let selected=APP.services[0];
const CLP=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
function init(){document.getElementById('brandName').textContent=APP.brand;document.getElementById('footerBrand').textContent=APP.brand;document.getElementById('therapistName').textContent=APP.therapist;document.getElementById('credentialName').textContent=APP.therapist;document.getElementById('therapistCredential').textContent=APP.credential;renderServices();handleReturn();}
function renderServices(){const root=document.getElementById('serviceList');root.innerHTML='';APP.services.forEach((s,i)=>{const el=document.createElement('button');el.type='button';el.className='service '+(s.id===selected.id?'active':'');el.innerHTML=`<span><strong>${s.name}</strong><small>${s.minutes} min · ${s.desc}</small></span><span class="servicePrice">${CLP(s.price)}</span>`;el.onclick=()=>{selected=s;renderServices()};root.appendChild(el)})}
function customer(){return{name:document.getElementById('name').value.trim(),email:document.getElementById('email').value.trim(),phone:document.getElementById('phone').value.trim(),region:document.getElementById('region').value,reason:document.getElementById('reason').value.trim()}}
document.getElementById('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const c=customer();if(!c.name||!c.email)return;sessionStorage.setItem('psyCustomer',JSON.stringify(c));sessionStorage.setItem('psyService',JSON.stringify(selected));const btn=document.getElementById('reserveBtn');btn.disabled=true;btn.textContent='Preparando pago…';try{if(!APP.payBeforeBooking){unlockBooking(c);return}const r=await fetch('/api/create-payment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({service:selected,customer:c,returnUrl:location.origin+location.pathname})});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo iniciar el pago');if(data.init_point){location.href=data.init_point}else if(data.demo_url){location.href=data.demo_url}else throw new Error('Respuesta de pago incompleta')}catch(err){alert(err.message+'\n\nSi estás abriendo el HTML directamente, despliega el repositorio en Vercel para activar las funciones serverless.');btn.disabled=false;btn.textContent='Continuar con la reserva'}});
async function handleReturn(){const q=new URLSearchParams(location.search);const payment=q.get('payment');if(!payment)return;const c=JSON.parse(sessionStorage.getItem('psyCustomer')||'{}');if(payment==='demo-approved'){unlockBooking(c);history.replaceState({},'',location.pathname+'#agenda');return}const paymentId=q.get('payment_id')||q.get('collection_id');if((payment==='success'||q.get('status')==='approved')&&paymentId){try{const r=await fetch('/api/payment-status?id='+encodeURIComponent(paymentId));const d=await r.json();if(d.approved){unlockBooking(c);history.replaceState({},'',location.pathname+'#agenda')}}catch(e){console.warn(e)}}}
function unlockBooking(c={}){document.getElementById('bookingUnlocked').classList.add('on');document.querySelectorAll('.stepDot')[1].classList.add('on');const box=document.getElementById('calContainer'),demo=document.getElementById('demoSlots');if(APP.calBookingUrl){const u=new URL(APP.calBookingUrl);if(c.name)u.searchParams.set('name',c.name);if(c.email)u.searchParams.set('email',c.email);box.innerHTML=`<iframe title="Agenda" src="${u}" style="width:100%;height:720px;border:0;border-radius:16px" loading="lazy"></iframe>`;document.getElementById('calendarHint').textContent='Selecciona directamente una hora disponible.'}else{document.getElementById('calendarHint').textContent='Modo demo: conecta tu URL de Cal.com en APP.calBookingUrl para mostrar disponibilidad real.';demo.innerHTML=['Mar 10:00','Mar 18:30','Mié 12:00','Jue 09:30','Jue 19:00','Vie 16:30'].map(x=>`<button class="slot" type="button" onclick="alert('Demo: ${x}. En producción esta acción la gestiona Cal.com.')">${x}</button>`).join('')}location.hash='agenda'}
init();
